### ISSUE TITLE
Find nearest gel tile on floor collision

### ISSUE THREAD

**Issue by Critfish** [alesan99/mari0_ae#122]
In Mari0, gel only affects the player if their hitbox is fully touching the gel, like this:
![image](https://user-images.githubusercontent.com/58682909/120881530-e47b6300-c610-11eb-812a-5d6022a70566.png)

If the player's hitbox is not fully touching the gel, the gel does not affect them. This can make repulsion gel more finicky to use, as the player needs to land practically dead-center for the gel to bounce them. In the case of Propulsion Gel, this causes the player to immediately decelerate upon running over a gel-coated ledge, forcing the player to time a jump, which can be annoying to pull off in some cases.

**Comment by WilliamFr0g** [comment]
Gel, like so many things, works by collision priority. Tiles on the left are older and thus collide first. So if the left side of Mario's hitbox is over an ungelled tile, he will collide with it first and stop without making contact with the gelled one at all. The same goes for the right side of gel areas. Except this time, since the left side is considered first, Mario only need to be barely touching the gel in order to bounce. Really this isn't a gel bug, but a deeper issue with the physics. This same effect can be witnessed with other types of interactive tiles, such as spikes.

**Comment by WilliamFr0g** [comment]
![Spike Imbalance](https://user-images.githubusercontent.com/83377256/120907497-fa4c5080-c62f-11eb-91a9-b34fc48cf3b0.gif)
Here we can see it in effect on spike tiles

**Comment by WilliamFr0g** [comment]
![image](https://user-images.githubusercontent.com/83377256/120907820-ba3a9d00-c632-11eb-9932-84ad3314d793.png)
Similarly, in this screenshot, both Marios are perfectly centered between the tiles. Left Mario will bounce on the gel and never touch the spikes, while Right Mario will die to the spikes without even considering the gel.

**Comment by alesan99** [comment]
It is an unfortunate problem with mari0's physics, but there is a simple way around it. I believe I did a fix for ice which was facing the same problem.

**Comment by alesan99** [comment]
9f1fc3cdaa7e04591072209057609eeec50b4209
