### ISSUE TITLE
Fuzzies Ignore Portals

### ISSUE THREAD

**Issue by poudink** [alesan99/mari0_ae#370]
See this example in world 1-3 of the new bundled level pack:
![image](https://user-images.githubusercontent.com/29778535/160613047-d9d44109-db89-434c-92e2-1f3aca7e5b3f.png)
Despite the Fuzzy very much going through the wall with the blue portal on it, it won't go through it to the orange portal and will simply go right past it.

**Comment by poudink** [comment]
![image](https://user-images.githubusercontent.com/29778535/160640920-94a60905-1023-4c3a-8151-908ad63818f8.png)
Also happens when they're not on tracks

**Comment by alesan99** [comment]
Tracked entities aren't portalable and weren't exactly designed to be. They appear to go through the portal simply due to the rendering order, and changing that for every entity more trouble than it's worth.
I'll leave that the way it is but I will however make them portalable when they're off the tracks to be consistent with goombas and other enemies.

**Comment by alesan99** [comment]
860b571bc69b9e983514711baa49ecc30a3fdf06
