### ISSUE TITLE
Horizontal Portal Misalignment

### ISSUE THREAD

**Issue by poudink** [alesan99/mari0_ae#371]
![image](https://user-images.githubusercontent.com/29778535/160613553-e6414214-f749-4146-be2f-b62178755248.png)
When Mario is partway through a vertical portal connected to a horizontal portal, the part of his body going out of the horizontal portal is misaligned. With big Mario, you'll usually stick out by a little over half a tile. Here with Yoshi, it's almost a full tile. Very distracting. This issue also appeared in the original Mari0.

**Comment by alesan99** [comment]
_Very_ distracting? I'm not sure. It certainly seems unpolished but for most of the game you aren't forced to look at it for more than a second, even during puzzles.
This is mostly a result of the game not having rotating hitboxes and being forced to orient the same sprite onto a different hitbox. Yoshi is a special case too because it hijacks the player's sprite in a weird way. A lot context-sensitive math would have to be added to the already messy old portal rendering code that it simply isn't worth the time.
