### ISSUE TITLE
Feature Request: Nearest Neighbor Scaling

### ISSUE THREAD

**Issue by poudink** [alesan99/mari0_ae#372]
With retro-looking games like this, I like the look of hard, sharp pixels the best, so I always go for unfiltered scaling. Unfortunately, this game only allows unfiltered scaling when using one of the integer scaling options (1x, 2x, 3x or 4x), meaning you can't have nearest neighbor scaling in full screen, for instance. I tried using the "pixellate" shaders, but they didn't appear to do... well, anything at all. This is far from an urgent request, as the scaling filter currently being used isn't very offensive. I would still appreciate it, though.

**Comment by WilliamFr0g** [comment]
I wouldn't recommend using anything other than integer scales in the first place, but I haven't experienced fuzziness in resizable. You might need to change the high dpi settings if you're on windows (right click the app > compatibility > Change high dpi settings > set high dpi scaling override to application)

**Comment by alesan99** [comment]
> You might need to change the high dpi settings if you're on windows (right click the app > properties > compatibility > Change high dpi settings > check the bottom box and make sure high dpi scaling override is set to application)
That was my suspicion at first too (and it still may help), but there is some fuzziness on my end while in proper full screen when I compare it to resizable full screen. I still think it looks quite sharp but I don't know if it may appear worse on some displays.
It's been years since I implemented it but I think this happens because scaling in full screen isn't handled by the game itself 
(it's passed off to whatever process your computer uses to scale full screen programs) unlike resizable mode, so it's not like I specifically chose to use a worse filter. I can make it so the game is scaled to the monitor's native resolution, which might be a waste of resources for a very small change, but it is technically possible.

**Comment by WilliamFr0g** [comment]
I'm sure it's just their dpi. "Normal" full screen _is_ still a tiny bit fuzzy, but it's not any worse than normal scales with dpi settings off.

**Comment by poudink** [comment]
I'm not on Windows, I'm on Linux.
