### ISSUE TITLE
Hans appears twice on the credits

### ISSUE THREAD

**Issue by Aid0nModder** [alesan99/mari0_ae#479]
Hans1998 and HansAgain are the same person (Shocking)

Also the uh, I noticed that two of your favorite contributors are missing. Some pineapple and blue mario.

**Comment by alesan99** [comment]
I had already fixed that in main.lua, updated the forum one.
I think the best option is to remove the credit section on the github readme since its incredibly annoying to have to update 3 separate pages every time I want to update something. It will always be available in the files themselves as well as the forum page, and the github contributors are already listed automatically on here.
