### ISSUE TITLE
Fix Only one koopa shell dying when two collide with eachother

### ISSUE THREAD

**Issue by alesan99** [alesan99/mari0_ae#87]

**Comment by Alexis0159** [comment]
I just extracted the koopa.lua file from Mari0 v1.6, I added it in the enemies folder of Mari0 AE but instead of replacing it I rename it to koopav1_6.lua and it seems to fix that problem but it breaks other things, I was checking the code and there seems to be something broken between koopa: leftcollide and koopa: rightcollide

**Comment by alesan99** [comment]
> I just extracted the koopa.lua file from Mari0 v1.6, I added it in the enemies folder of Mari0 AE but instead of replacing it I rename it to koopav1_6.lua and it seems to fix that problem but it breaks other things, I was checking the code and there seems to be something broken between koopa: leftcollide and koopa: rightcollide

You don't have to look into it that much, it's really not that complicated of an issue. I just haven't gotten around to it because it doesn't break anything and I have many other more important issues.

**Comment by alesan99** [comment]
539b97e50a2532b23bcb12ea9ba68b6d1e583f7d
