### ISSUE TITLE
Improvements/Additions to Mario Maker Physics

### ISSUE THREAD

**Issue by TheMushrunt** [alesan99/mari0_ae#91]
with super mario bros. 35's physics being yet another variation of the super mario bros. physics, i feel like some of its features should be added onto the mario maker physics to prevent a 7th (and probably 8th) new physics option. i also feel like some things from the mario maker physics should be tweaked/improved.

things that i feel should be added:
-going from small to fire should play the growing animation and the palette cycle simultaneously. i know this could be a bit of a challenge but i think it looks cleaner than just turning the player into their big form and preforming the palette cycle.
-taking damage (going from a non-mushroom power-up down to their big form) should pause gameplay like it does for going from their big form to their small form.

changes i feel should be made:
-instead of having the player flash when taking damage in a state higher than big mario, or having the player do the star palette cycle when collecting a power-up other than a mushroom, i feel like it could switch between the two different forms. (i also feel like this could fix that bug where different forms are playing animations that they don't have, leading to stretched sprites)
-the fastest falling gravity doesn't feel all that fast compared to actual mario maker gameplay. maybe the limit on the maximum gravity could be increased?

**Comment by WilliamFr0g** [comment]
Tbh I never paid the grow/shrink animations much mind, but I think the fall speeds are accurate. I find that it feels almost like gliding when you're transitioning from the fast falling physics, because of how fast you fell before, but after using it for more time it feels more normal. The slower max fall speed is 15, which is the same speed as fireballs go horizontally. Shooting fireballs makes them fall at a 45° angle pretty consistently across Mario games, so I think the fall speed is correct already.
