### ISSUE TITLE
"Small Icicle" Issue

### ISSUE THREAD

**Issue by TheMushrunt** [alesan99/mari0_ae#92]
i feel like the small icicle should be improved, maybe as a separate entity from the current one to prevent compatibility problems.

the way it works is unchanged from when the only icicles that existed were Super Mario Bros. Special's.

as a solution, maybe it could be worked off of the mario maker/big icicle?

with the way it is right now, the options for whether or not it can fall, as well as its gravity don't make much sense, especially when considering that there isn't even an option for it being able to stay still, despite graphics for it existing. i feel like these should be "brought over" from the other icicle, too.

**Comment by alesan99** [comment]
They are meant to function differently, they'd lack much use if they behaved the same.
But I do understand the graphic change doesn't exactly convey that.

If I were to improve them in any way I'd make the gravity option a slider. And the extra graphic is only there because it uses the same sprite format as goombas, but I could add a 'not fall' option too

**Comment by LeanneTM** [comment]
nice ideas.. id also like for them to throw 2 small icicle pieces as well so they dont simply disappear..
